
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - blog-storage:/usr/src/app/storage/thumbnails
    ports:
      - "8001:8001"  # Map host port 8001 to container port 8001 jnjbuikbbk jsmnbhgvshgdcg

volumes:
  blog-storage:
