name: CI/CD Pipeline for Blog App (DockerHub Only)

on:
  push:
    branches:
      - main  # This will trigger the pipeline when code is pushed to the `main` branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu in this case)

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v4  # Use GitHub's official checkout action

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Set up Docker Buildx to enable multi-platform builds

      # Step 3: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3  # Login to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Get DockerHub username from GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Get DockerHub password from GitHub secrets

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5  # Use the Docker build and push action
        with:
          context: .  # Path to the build context (current directory)
          push: true  # Push the built image to DockerHub
          tags: ${{ secrets.DOCKER_USERNAME }}/blog:latest  # Docker image tag (uses the Docker username from secrets)

      # Optional: Print Docker version for troubleshooting
      - name: Print Docker Version
        run: docker --version  # Print the Docker version to verify that Docker is working correctly
